name: Sync to Private Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Exit if this is not Public Repository
      if: ${{ github.repository != 'lichen63/lichen63.github.io' }}
      run: echo "Not running in Public Repository. Exiting..." && exit 0

    - name: Checkout Current Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Verify Token Access
      run: |
        echo "Verifying token access..."
        curl -H "Authorization: token ${{ secrets.SYNC_PRIVATE_REPO_TOKEN }}" https://api.github.com/repos/lichen63/lichen63.github.io-private

    - name: Remove Workflow Files Before Sync
      run: |
        rm -rf .github/workflows
        git rm -r --cached .github/workflows || true
        git commit -m "Remove workflows before syncing" || true

    - name: Push to Private Repository
      run: |
        git config --global user.name "SyncBot from Public Repo"
        git config --global user.email "syncbot@github-actions.github.io"
        git remote add PrivateRepo https://x-access-token:${{ secrets.SYNC_PRIVATE_REPO_TOKEN }}@github.com/lichen63/lichen63.github.io-private.git

        git fetch PrivateRepo main
        git merge PrivateRepo/main --allow-unrelated-histories --no-edit
        git push PrivateRepo main